name: Renku Docker Image CI

on: [push]

jobs:

  build-py:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v2
    - name: Build renku project python-based docker images
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        docker build docker/py --tag $DOCKER_NAME-py:3.8-$LABEL
        docker push $DOCKER_NAME-py:3.8-$LABEL

        # on master push latest image
        if [ "$REF" == "refs/heads/master" ]
        then
          docker tag $DOCKER_NAME-py:3.8-$LABEL $DOCKER_NAME-py:latest
          docker push $DOCKER_NAME-py:latest
        fi
      env:
        DOCKER_NAME: "renku/renkulab"

  build-py-ext:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        EXTENSIONS:
          - cuda9.2
          - cuda10.0-tf
          - julia1.3.1

    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v2
    - name: Build renku project python-based docker image extensions
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        docker build docker/$EXTENSION \
          --build-arg BASE_IMAGE="$DOCKER_NAME-py:3.8-$LABEL" \
          --tag $DOCKER_NAME-$EXTENSION:$LABEL
        docker push $DOCKER_NAME-$EXTENSION:$LABEL
      env:
        EXTENSION: ${{ matrix.EXTENSIONS }}
        DOCKER_NAME: "renku/renkulab"

  build-r-ubuntu:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        RVERSIONS:
          - 4.0.3
    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v2
    - name: Build renku project rocker docker images
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        export DOCKER_TAG="$RVERSION-$LABEL"
        docker build docker/r \
          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.8-$LABEL" \
          --build-arg BASE_IMAGE="rocker/verse:${RVERSION}" \
          --tag $DOCKER_NAME-r:$DOCKER_TAG
        docker push $DOCKER_NAME-r:$DOCKER_TAG

        # on master push latest image
        if [ "$REF" == "refs/heads/master" ] && [ "$RVERSION" == "4.0.3" ]
        then
          docker tag $DOCKER_NAME-r:$DOCKER_TAG $DOCKER_NAME-r:latest
          docker push $DOCKER_NAME-r:latest
        fi
      env:
        DOCKER_NAME: "renku/renkulab"
        # selected R versions available for rocker/rstudio
        RVERSION: ${{ matrix.RVERSIONS }}

  build-bioc:
    needs: build-py
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        RELEASES:
          - devel
          - RELEASE_3_11
    steps:
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v2
    - name: Build renku project bioconductor docker images
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi

        export DOCKER_TAG="$RELEASE-$LABEL"
        docker build docker/r \
          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.8-$LABEL" \
          --build-arg BASE_IMAGE=bioconductor/bioconductor_docker:${RELEASE} \
          --tag $DOCKER_NAME-bioc:$DOCKER_TAG
        docker push $DOCKER_NAME-bioc:$DOCKER_TAG

        # on master push latest image
        if [ "$REF" == "refs/heads/master" ] && [ "$RELEASE" == "devel" ]
        then
          docker tag $DOCKER_NAME-bioc:$DOCKER_TAG $DOCKER_NAME-bioc:latest
          docker push $DOCKER_NAME-bioc:latest
        fi
      env:
        DOCKER_NAME: "renku/renkulab"
        RELEASE: ${{ matrix.RELEASES }}
